{% set name = "aiosignal" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/aiosignal-{{ version }}.tar.gz
  sha256: f47eecd9468083c2029cc99945502cb7708b082c232f9aca65da147157b251c7

build:
  number: 0
  skip: true  # [py<37]
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python
    - wheel
  run:
    - frozenlist >=1.1.0
    - python

test:
  source_files:
    - tests
  imports:
    - aiosignal
  requires:
    - pip
    - pytest
    - pytest-asyncio
    - pytest-cov
  commands:
    - pip check
    - pytest -v tests/ --asyncio-mode=auto

about:
  home: https://github.com/aio-libs/aiosignal
  summary: "aiosignal: a list of registered asynchronous callbacks"
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  dev_url: https://github.com/aio-libs/aiosignal
  doc_url: https://aiosignal.readthedocs.io/en/stable/

extra:
  recipe-maintainers:
    - ocefpaf
